>Finance
    >.next
    >actions
        -actions/account.js
        -actions/budget.js
        -actions/dashboard.js
        -actions/seed.js
        -actions/send-email.js
        -actions/transaction.js
    >app
        -app/(auth)/layout.js
        -app/(auth)/sign-in/[[...sign-in]]/page.jsx
        -app/(auth)/sign-up/[[...sign-up]]/page.jsx
        -app/(main)/layout.js
        -app/(main)/account/_components/account-chart.jsx
        -app/(main)/account/_components/no-pagination-transaction-table.jsx
        -app/(main)/account/_components/transaction-table.jsx
        -app/(main)/account/[id]/page.jsx
        -app/(main)/dashboard/_components/account-card.jsx
        -app/(main)/dashboard/_components/budget-progress.jsx
        -app/(main)/dashboard/_components/transaction-overview.jsx
        -app/(main)/dashboard/layout.js
        -app/(main)/dashboard/page.jsx
        -app/(main)/transaction/layout.js
        -app/(main)/transaction/_components/recipt-scanner.jsx
        -app/(main)/transaction/_components/transaction-form.jsx
        -app/(main)/transaction/create/page.jsx
        -app/api/inngest/route.js
        -app/api/seed/route.js
        -app/lib/schema.js
        -app/page.jsx
        -app/not-found.jsx
        -app/layout.js
        -app/globals.css
    >components
        -components/create-account-drawer.jsx
        -components/header.jsx
        -components/hero.jsx
        -components/ui/badge.jsx
        -components/ui/button.jsx
        -components/ui/calendar.jsx
        -components/ui/card.jsx
        -components/ui/chart.jsx
        -components/ui/checkbox.jsx
        -components/ui/drawer.jsx
        -components/ui/dropdown-menu.jsx
        -components/ui/input.jsx
        -components/ui/popover.jsx
        -components/ui/progress.jsx
        -components/ui/select.jsx
        -components/ui/sooner.jsx
        -components/ui/switch.jsx
        -components/ui/table.jsx
        -components/ui/tooltip.jsx
    >data
        -data/categories.js
        -data/landing.js
    >emails
        -emails/template.jsx
    >hooks
        -hooks/use-fetch.js
    >lib
        -lib/inngest/client.js
        -lib/inngest/function.js
        -lib/arcjet.js
        -lib/checkUser.js
        -lib/prisma.js
        -lib/utils.js
    >node_modules
    >prisma
        -prisma/migrations
        -prisma/schema.prisma
    >public

This is how my project file looks so tell me where to add files according to file structure.